In [1]:
import torch

In [2]:
x = torch.tensor([1.], requires_grad=True)

In [3]:
loss = x ** 3 + 2 * (x ** 2) + 5 * x + 7

In [4]:
dx_loss = torch.autograd.grad(loss, x)[0]

In [5]:
dx_loss

tensor([12.])

In [7]:
# This will generate error
# dx_dx_loss = torch.autograd.grad(dx_loss, x)[0]

In [8]:
x = torch.tensor([1.], requires_grad=True)

In [9]:
loss = x ** 3 + 2 * (x ** 2) + 5 * x + 7

In [10]:
# This create_graph will allow generating second derivative
dx_loss = torch.autograd.grad(loss, x, create_graph=True)[0]

In [11]:
dx_loss

tensor([12.], grad_fn=<AddBackward0>)

In [12]:
dx_dx_loss = torch.autograd.grad(dx_loss, x)[0]

In [13]:
dx_dx_loss

tensor([10.])